import path from "node:path";
import { mkdir, readFile, readdir, stat, writeFile } from "node:fs/promises";

function root() { const value = process.env.FIREBOX_PROJECTS_ROOT; if (!value) throw new Error("FIREBOX_PROJECTS_ROOT is not configured"); return path.resolve(value); }
function safe(value: string, label: string) { if (!/^[a-zA-Z0-9_-]+$/.test(value)) throw new Error(`Invalid ${label}`); return value; }
export function workspacePath(userId: string, projectId: string, relativePath = "") { const workspace = path.resolve(root(), safe(userId, "user"), safe(projectId, "project")); const target = path.resolve(workspace, relativePath); if (target !== workspace && !target.startsWith(`${workspace}${path.sep}`)) throw new Error("Path escapes project workspace"); return { workspace, target }; }
export async function ensureWorkspace(userId: string, projectId: string) { const { workspace } = workspacePath(userId, projectId); await mkdir(workspace, { recursive: true }); return workspace; }
export async function listWorkspace(userId: string, projectId: string, relativePath = "") { const { workspace, target } = workspacePath(userId, projectId, relativePath); const entries = await readdir(target, { withFileTypes: true }); return Promise.all(entries.filter((entry) => !["node_modules", ".git", "dist"].includes(entry.name)).map(async (entry) => { const full = path.join(target, entry.name); return { path: path.relative(workspace, full).replaceAll("\\", "/"), type: entry.isDirectory() ? "directory" : "file" }; })); }
export async function readWorkspaceFile(userId: string, projectId: string, relativePath: string) { return readFile(workspacePath(userId, projectId, relativePath).target, "utf8"); }
export async function writeWorkspaceFile(userId: string, projectId: string, relativePath: string, content: string) { const { target } = workspacePath(userId, projectId, relativePath); await mkdir(path.dirname(target), { recursive: true }); await writeFile(target, content, "utf8"); }
export async function analyzeWorkspace(userId: string, projectId: string) { const { workspace } = workspacePath(userId, projectId); const detected: Record<string, unknown> = { framework: null, language: null, runtime: null, packageManager: null, buildTool: null, devCommand: null, buildCommand: null, filesPath: workspace }; let packageJson: any; try { packageJson = JSON.parse(await readFile(path.join(workspace, "package.json"), "utf8")); const dependencies = { ...(packageJson.dependencies ?? {}), ...(packageJson.devDependencies ?? {}) }; detected.language = "TypeScript" in dependencies || await exists(path.join(workspace, "tsconfig.json")) ? "TypeScript" : "JavaScript"; detected.runtime = "Node.js"; detected.packageManager = await exists(path.join(workspace, "pnpm-lock.yaml")) ? "pnpm" : await exists(path.join(workspace, "yarn.lock")) ? "yarn" : "npm"; detected.framework = dependencies.next ? "Next.js" : dependencies["@vitejs/plugin-react"] || dependencies.react ? "React" : dependencies["@sveltejs/kit"] ? "SvelteKit" : dependencies.express ? "Express" : null; detected.buildTool = dependencies.vite ? "Vite" : dependencies.next ? "Next.js" : null; detected.devCommand = packageJson.scripts?.dev ?? null; detected.buildCommand = packageJson.scripts?.build ?? null; } catch {} if (!packageJson && await exists(path.join(workspace, "requirements.txt"))) { detected.language = "Python"; detected.runtime = "Python"; detected.packageManager = "pip"; detected.framework = await exists(path.join(workspace, "pyproject.toml")) ? "Python" : null; } if (await exists(path.join(workspace, "go.mod"))) { detected.language = "Go"; detected.runtime = "Go"; detected.packageManager = "go modules"; } return detected; }
async function exists(value: string) { try { await stat(value); return true; } catch { return false; } }
