// @ts-nocheck
import { Router } from "express";
import { randomUUID } from "node:crypto";
import { authMiddleware, type AuthenticatedRequest } from "../middlewares/auth";
import { activities, deployments, projects, users, type ProjectDocument } from "../services/mongo";
import { ensureWorkspace } from "../services/workspace";

const router = Router(); router.use(authMiddleware);
const colors = ["#7c5cff", "#f0a34a", "#35b997", "#1c1d25"];
const projectView = (p: ProjectDocument) => ({ ...p, id: p._id, updatedAt: p.updatedAt.toISOString() });
router.get("/profile", (req: AuthenticatedRequest, res) => res.json(req.user));
router.patch("/profile", async (req: AuthenticatedRequest, res) => { const name = typeof req.body?.name === "string" ? req.body.name.trim() : ""; if (!name) return res.status(400).json({ error: "A display name is required" }); await (await users()).updateOne({ _id: req.user!.id }, { $set: { name } }); res.json({ ...req.user, name }); });
router.get("/dashboard", async (req: AuthenticatedRequest, res) => { const userId = req.user!.id; const [projectCount, deploymentCount, recentActivity] = await Promise.all([(await projects()).countDocuments({ userId }), (await deployments()).countDocuments({ userId }), (await activities()).find({ userId }).sort({ timestamp: -1 }).limit(5).toArray()]); res.json({ projects: projectCount, deployments: deploymentCount, activeRuns: 0, recentActivity: recentActivity.map((a) => ({ ...a, id: a._id, timestamp: a.timestamp.toISOString() })), usage: null }); });
router.get("/projects", async (req: AuthenticatedRequest, res) => res.json((await (await projects()).find({ userId: req.user!.id }).sort({ updatedAt: -1 }).toArray()).map(projectView)));
router.post("/projects", async (req: AuthenticatedRequest, res) => { const { name, source, prompt = null, repository = null, framework } = req.body ?? {}; if (typeof name !== "string" || !name.trim() || !["prompt", "github", "zip"].includes(source)) return res.status(400).json({ error: "A project name and valid source are required" }); const now = new Date(); const project: ProjectDocument = { _id: randomUUID(), userId: req.user!.id, name: name.trim(), slug: name.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""), source, framework: typeof framework === "string" && framework ? framework : "Unknown", runtime: "Unknown", status: source === "prompt" ? "ready" : "needs-setup", updatedAt: now, color: colors[Math.floor(Math.random() * colors.length)], description: typeof prompt === "string" ? prompt : null, repository: typeof repository === "string" ? repository : null }; try { await ensureWorkspace(project.userId, project._id); } catch (error) { return res.status(503).json({ error: error instanceof Error ? error.message : "Workspace storage unavailable" }); } await (await projects()).insertOne(project); await (await activities()).insertOne({ _id: randomUUID(), userId: project.userId, projectId: project._id, label: "Project created", detail: project.name, status: "complete", timestamp: now }); res.status(201).json(projectView(project)); });
router.get("/projects/:projectId", async (req: AuthenticatedRequest, res) => { const project = await (await projects()).findOne({ _id: req.params.projectId, userId: req.user!.id }); if (!project) return res.status(404).json({ error: "Project not found" }); res.json(projectView(project)); });
router.patch("/projects/:projectId", async (req: AuthenticatedRequest, res) => { const name = typeof req.body?.name === "string" ? req.body.name.trim() : ""; if (!name) return res.status(400).json({ error: "A project name is required" }); const result = await (await projects()).findOneAndUpdate({ _id: req.params.projectId, userId: req.user!.id }, { $set: { name, slug: name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""), updatedAt: new Date() } }, { returnDocument: "after" }); if (!result) return res.status(404).json({ error: "Project not found" }); res.json(projectView(result)); });
router.delete("/projects/:projectId", async (req: AuthenticatedRequest, res) => { const result = await (await projects()).deleteOne({ _id: req.params.projectId, userId: req.user!.id }); if (!result.deletedCount) return res.status(404).json({ error: "Project not found" }); await Promise.all([(await activities()).deleteMany({ projectId: req.params.projectId, userId: req.user!.id }), (await deployments()).deleteMany({ projectId: req.params.projectId, userId: req.user!.id })]); res.status(204).end(); });
router.get("/projects/:projectId/activity", async (req: AuthenticatedRequest, res) => { const list = await (await activities()).find({ projectId: req.params.projectId, userId: req.user!.id }).sort({ timestamp: -1 }).toArray(); res.json(list.map((a) => ({ ...a, id: a._id, timestamp: a.timestamp.toISOString() }))); });
router.get("/templates", (_req, res) => res.json([])); router.get("/deployments", async (req: AuthenticatedRequest, res) => res.json((await (await deployments()).find({ userId: req.user!.id }).toArray()).map((d) => ({ ...d, id: d._id, createdAt: d.createdAt.toISOString() }))));
export default router;
